apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocdapplicationset
  # namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/Trev2689/argocd.git
      revision: HEAD
      directories:
      - path: usw2/usw2-td1/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: anubis
      source:
        repoURL: https://github.com/Trev2689/argocd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
          automated:
              allowEmpty: true
              prune: true
              selfHeal: true
          syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
