apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd2

resources:
- namespace.yaml
- project.yaml

helmCharts:
- name: argo-cd
  version: 6.8.0
  releaseName: argocd
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
  namespace: argocd2
