apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: anubis
spec:
  orphanedResources:
    warn: false
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
