apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wednesday-vault
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
      app.kubernetes.io/instance: wednesday-vault
  namespaceSelector:
    matchNames:
      - wednesday-vault
  endpoints:
    - interval: 30s
      path: /v1/sys/metrics
      port: https
      scheme: https
      tlsConfig:
        insecureSkipVerify: true # Set here as its only scraping the vault metrics endpoint(which itself is not secured), not vault itself and its only inside the cluster.
