apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: copenhagen-ingress-route-tcp
  namespace: copenhagen-vault
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`copenhagen.anubisdev.inday.io`)
    services:
    - name: copenhagen-vault-active
      port: 8200
  tls:
    passthrough: true
