apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: copenhagen-vault

configMapGenerator:
- name: kustomize-configmap
  namespace: copenhagen-vault
  files:
    - samplevalues.yaml
  options:
    disableNameSuffixHash: true
  
# transformers:
# - apiVersion: builtin
#   kind: ConfigMapRefGenerator
#   metadata:
#     name: kustomize-configmap
#     namespace: copenhagen-vault
#   behavior: merge



resources:
- backup.yaml
- service-monitor.yaml
- ingressroute.yaml
- configmap.yaml
- vault-cert.yaml
- values-configmap.yaml




helmCharts:
- name: vault
  version: 0.27.0  # Specify the version of the HashiCorp Vault Helm chart
  releaseName: copenhagen
  repo: https://helm.releases.hashicorp.com
  valuesFile: values.yaml  # Path to your custom values.yaml file
  namespace: copenhagen-vault  # Namespace where the HashiCorp Vault should be installed
