apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: copenhagen
    app.kubernetes.io/name: vault
    thisnamespace: $(kustomize-configmap.namespace)
    release: prometheus
  name: copenhagen-vault-argo
  namespace: copenhagen-vault
spec:
  endpoints:
    - interval: 30s
      params:
        format:
          - prometheus
      path: /v1/sys/metrics
      port: https
      scheme: https
      scrapeTimeout: 10s
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - copenhagen-vault
  selector:
    matchLabels:
      app.kubernetes.io/instance: copenhagen
      app.kubernetes.io/name: vault
