apiVersion: v1
kind: ConfigMap
metadata:
  name: test-kustomize
  namespace: copenhagen-vault
data:
  namecustom: "placeholder"  # Placeholder value
  namespace: "placeholder"   # Placeholder value
  # Add other data as needed
valuesFrom:
- configMapRef:
    name: kustomize-configmap
