apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-instances
spec:
  generator:
    list:
      elements:
        - name: dublin-vault
          values:
            repository: https://github.com/Trev2689/vault
            revision: main
            path: us-west-2/eks-td1/dublin-vault-values.yaml
        - name: kildare-vault
          values:
            repository: https://github.com/Trev2689/vault
            revision: main
            path: us-west-2/eks-td1/kildare-vault-values.yaml
        # Add more elements as needed
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
    spec:
      project: vault-app-project
      source:
        repoURL: https://helm.releases.hashicorp.com
        chart: vault
        targetRevision: 0.27.0
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{item.name}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      helm:
        values: |
          {{- include (download item.values.repository item.values.revision item.values.path) . | nindent 10 }}
